//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionReport
    {
        public int Id { get; set; }
        public string Vin { get; set; }
        public string ProductionYear { get; set; }
        public string Model { get; set; }
    }
}
